### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by marchchad** [iboates/android_location_converter#1]
There's reference to a "master_dict" after the return statement [here](https://github.com/iboates/android_location_converter/blob/master/read_location_data.py#L55-L58). This variable is unknown but also the code is unreachable due to the return statement at [line 53](https://github.com/iboates/android_location_converter/blob/master/read_location_data.py#L55-L58)

**Comment by iboates** [comment]
Thanks for pointing that out.  It was a leftover from when I had originally written the function.
